(function() {
    'use strict';

    angular.module('app', [
        // Shared modules
        'app.core',
        'app.router',
        'app.layout',
        'app.templates',  // Generated by Gulp

        // Feature modules
        'app.about',
        'app.error',
        'app.vocabulary',
        'app.authority',
        'app.catalogue',
    ]);

})();
